name: Gradle Run for Lab Environment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Thundra Gradle Test Instrumentation
      uses: thundra-io/thundra-gradle-test-action@v1
      with:
        apikey: ${{ secrets.THUNDRA_APIKEY }}
        project_id: ${{ secrets.THUNDRA_PROJECTID }}
    - name: Run Gradle command
      run: ./gradlew build --init-script $THUNDRA_GRADLE_INIT_SCRIPT_PATH
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
          THUNDRA_AGENT_BROKER_ENABLE: false
          THUNDRA_AGENT_REPORT_UPLOAD_REST_URL: https://upload.thundra.me