name: Maven Run for Staging Environment

on:
  schedule:
    - cron: "0 7,19 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Thundra Maven Test Instrumentation Action
        uses: thundra-io/thundra-maven-test-action@v1
        with:
          apikey: ${{ secrets.THUNDRA_APIKEY }}
          project_id: ${{ secrets.THUNDRA_PROJECTID }}
          command: mvn -B clean install
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.us/v1
          THUNDRA_AGENT_BROKER_ENABLE: false
          THUNDRA_AGENT_REPORT_UPLOAD_REST_URL: https://upload.thundra.us
