name: Java CI with Maven for thundra-demo-todo-app-java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Thundra Maven Test Instrumentation Action
        uses: thundra-io/thundra-maven-test-action@prep-for-release
        with:
          apikey: ${{ secrets.THUNDRA_DEMO_APIKEY }}
          command: mvn -B clean install
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
          THUNDRA_AGENT_TEST_PROJECT_ID: f5a62856-49b3-46e8-8b0c-49f219d1270b
          THUNDRA_AGENT_BROKER_ENABLE: false
